sudo: required
language: cpp
dist: bionic
matrix:
  include:
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-7
    - CC_COMPILER=gcc-7
    - FC_COMPILER=gfortran-7
    - OMPI_CC=gcc-7
    - OMPI_FC=gfortran-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - gfortran-7
before_install:
- sudo apt-get update
- sudo apt-get install python3
# Sonar preparation
- wget https://dl.bintray.com/sonarsource/SonarQube/org/sonarsource/scanner/cli/sonar-scanner-cli/4.6.0.2311/sonar-scanner-cli-4.6.0.2311-linux.zip
- unzip sonar-scanner-cli-4.6.0.2311-linux.zip
- export PATH=$PATH:$TRAVIS_BUILD_DIR/sonar-scanner-4.6.0.2311-linux/bin
- sonar-scanner --version
- wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
- unzip build-wrapper-linux-x86.zip
- export PATH=$PATH:$TRAVIS_BUILD_DIR/build-wrapper-linux-x86
- export SONAR_TOKEN=68fa8ff4cca8ae996661bed91f6f218e352174a3
before_script:
- export FC=$FC_COMPILER
- export CC=$CC_COMPILER
- export CXX=$CXX_COMPILER
script:
- echo "Testing out-of-source cmake build"
- export OMNI_SRC=$(pwd)
- export OMNI_BUILD=${OMNI_SRC}/build
- export OMNI_INSTALL=${HOME}/omni-install
- mkdir ${OMNI_BUILD}
- mkdir ${OMNI_INSTALL}
- cd ${OMNI_BUILD}
- cmake -S ${OMNI_SRC} -DCMAKE_INSTALL_PREFIX=${OMNI_INSTALL} -DPython3_EXECUTABLE=$(which python3)
- make -j
- make install
- make -j test-ffront-c
- make -j test-ffront-cpp
- echo "Testing in-source GNU Make build"
- cd ${OMNI_SRC}
- "./configure && make && make test"
- rm -rf ${OMNI_BUILD} && mkdir ${OMNI_BUILD} && cd ${OMNI_BUILD}
- cmake -S ${OMNI_SRC} -DCMAKE_INSTALL_PREFIX=${OMNI_INSTALL}
- NUMBER_OF_PROCESSORS=$(nproc --all)
# Wraps the compilation with the Build Wrapper to generate configuration (used
# later by the SonarQube Scanner) into the "bw-output" folder
- build-wrapper-linux-x86-64 --out-dir bw-output make -j ffront
# And finally run the SonarQube analysis - read the "sonar-project.properties"
# file to see the specific configuration
- cd ${OMNI_SRC}
- sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS}
